name: update
on:
  schedule:
    - cron:  '*/15 * * * *'
jobs:
  check:
    name: check
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm show firebase-tools version
