name: update
on:
  push
jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm show firebase-tools version
